name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  test-and-scan:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub에서 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js 설치 (Snyk CLI 설치를 위해)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Snyk CLI 설치
      - name: Install Snyk CLI
        run: |
          npm install -g snyk
          snyk --version

      # 4. Python 환경 설정
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 5. 필요한 Python 패키지 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 6. Snyk를 이용하여 코드 스캔
      - name: Run Snyk Code Scan
        run: snyk code test --json > snyk_results.json --debug
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # 7. Snyk 스캔 결과에 따라 Hugging Face AI 모델로 코드 수정
      - name: Check for vulnerabilities
        id: check_vulnerabilities
        run: |
          if grep -q "vulnerabilities" snyk_results.json; then
            echo "vulnerabilities_found=true" >> $GITHUB_ENV
          else
            echo "vulnerabilities_found=false" >> $GITHUB_ENV
          fi

      - name: Analyze and Fix Vulnerabilities with Hugging Face
        if: env.vulnerabilities_found == 'true'
        run: |
          python fix_vulnerabilities_with_huggingface.py snyk_results.json

      # 8. 수정된 코드가 있다면 GitHub에 푸시
      - name: Check if fixed code exists
        id: check_fixed_code
        run: |
          if [ -f "fixed_code.py" ]; then
            echo "fixed_code_exists=true" >> $GITHUB_ENV
          else
            echo "fixed_code_exists=false" >> $GITHUB_ENV
          fi

      - name: Commit and Push fixed code
        if: env.fixed_code_exists == 'true'
        run: |
          git config --local user.email "kkamagui.0@gmail.com"
          git config --local user.name "KKamgui-0"
          git add .
          git commit -m "Auto-fixed vulnerabilities"
          git push https://<YOUR_GITHUB_TOKEN>@github.com/KKamagui-0/Project_Joleeus.git HEAD:master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 9. 람다 함수 호출하여 SNS 알림 발송
      - name: Trigger Lambda for SNS Notification
        if: env.fixed_code_exists == 'true'
        run: |
          aws lambda invoke --function-name Vulnerability_Discovered --payload file://fixed_code.py response.json
          cat response.json

  deploy:
    runs-on: ubuntu-latest
    needs: test-and-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS Elastic Beanstalk CLI
        run: |
          pip install awsebcli

      # 8. Elastic Beanstalk 환경 상태 확인 및 생성
      - name: Check if Elastic Beanstalk Environment Exists
        id: check_env
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-northeast-2"
        run: |
          if eb status joleeus-env; then
            echo "env_exists=true" >> $GITHUB_ENV
          else
            echo "env_exists=false" >> $GITHUB_ENV
          fi

      - name: Create Elastic Beanstalk Environment if Not Found
        if: env.env_exists == 'false'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-northeast-2"
        run: |
          eb create joleeus-env --region ap-northeast-2 --platform "python-3.11" --single

      - name: Use Elastic Beanstalk Environment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-northeast-2"
        run: |
          eb use joleeus-env

      # 9. Elastic Beanstalk에 코드 배포
      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-northeast-2"
        run: |
          eb deploy



