name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  test-and-scan:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub에서 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js 설치 (Snyk CLI 설치를 위해)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Snyk CLI 설치
      - name: Install Snyk CLI
        run: |
          npm install -g snyk
          snyk --version

      # 4. Python 환경 설정
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 5. 필요한 Python 패키지 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 6. Snyk를 이용하여 코드 스캔
      - name: Run Snyk Code Scan
        run: snyk code test --json > snyk_results.json --debug
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # 7. Snyk 스캔 결과에 따라 Hugging Face AI 모델로 코드 수정
      - name: Analyze and Fix Vulnerabilities with Hugging Face
        if: always() && grep -q "vulnerabilities" snyk_results.json
        run: |
          python fix_vulnerabilities_with_huggingface.py snyk_results.json

      # 8. 수정된 코드가 있다면 GitHub에 푸시
      - name: Commit and Push fixed code
        if: always() && [ -f "fixed_code.py" ]
        run: |
          git config --local user.email "kkamagui.0@gmail.com"
          git config --local user.name "KKamgui-0"
          git add .
          git commit -m "Auto-fixed vulnerabilities"
          git push https://<YOUR_GITHUB_TOKEN>@github.com/KKamagui-0/Project_Joleeus.git HEAD:master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 9. 람다 함수 호출하여 SNS 알림 발송
      - name: Trigger Lambda for SNS Notification
        if: always() && [ -f "fixed_code.py" ]
        run: |
          aws lambda invoke --function-name Vulnerability_Discovered --payload file://fixed_code.py response.json
          cat response.json

  deploy:
    runs-on: ubuntu-latest
    needs: test-and-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Elastic Beanstalk
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ap-northeast-2"
        run: |
          pip install awsebcli
          eb init -p python-3.11 my-eb-app --region ap-northeast-2
          eb deploy --staged
